{
    "server" : {
        "tcpPort" : 14477,
        "udpPort" : 14476,
        "requestThreshold" : 20
    },
    "routes" : [ {
        "routeName" : "immobile-route-20a90a2e-a6ea-485e-9452-532b96bc0f4b",
        "blockedAddresses" : [ ],
        "addressFamily" : "LOCAL",
        "databaseName" : "ALTERDATA_IMMOBILE",
        "remoteAddress" : "-"
    }, {
        "routeName" : "pack0-route-81db1757-d2cb-4349-8158-2fc7d7a42871",
        "blockedAddresses" : [ ],
        "addressFamily" : "REMOTE",
        "databaseName" : "ALTERDATA_PACK",
        "remoteAddress" : "172.16.100.254"
    } ],
    "rules" : [ {
        "ruleOrder" : 10,
        "ruleName" : "rule-34b6acea-c800-4b07-9136-3ee408844209",
        "routeName" : "immobile-route-20a90a2e-a6ea-485e-9452-532b96bc0f4b",
        "command" : "any",
        "addressBlockIds" : [ "192.168.1.0-192.168.1.254" ],
        "ruleType" : "ACCEPT"
    }, {
        "ruleOrder" : 10,
        "ruleName" : "rule-b906f967-330d-43d1-ba27-d6880dd48ab0",
        "routeName" : "immobile-route-20a90a2e-a6ea-485e-9452-532b96bc0f4b",
        "command" : "any",
        "addressBlockIds" : [ "192.168.1.0-192.168.1.100" ],
        "ruleType" : "ACCEPT"
    } ]
}