---
requestThreshold: 20
routes:
- routeName: "immobile-route-5a5abc33-578c-4499-a4bf-04b6c803f2af"
  blockedAddresses: []
  addressFamily: "LOCAL"
  databaseName: "ALTERDATA_IMMOBILE"
  remoteAddress: "-"
- routeName: "pack0-route-b4e2de5e-22c3-4f1c-b088-b0e95cba8064"
  blockedAddresses: []
  addressFamily: "REMOTE"
  databaseName: "ALTERDATA_PACK"
  remoteAddress: "172.16.100.254"
rules:
- ruleOrder: 10
  ruleName: "rule-63ebb189-05dc-4a86-805c-4072ceb4447f"
  routeName: "immobile-route-5a5abc33-578c-4499-a4bf-04b6c803f2af"
  command: "any"
  addressBlockIds:
  - "192.168.1.0-192.168.1.254"
  ruleType: "ACCEPT"
- ruleOrder: 10
  ruleName: "rule-ef0c734b-58a6-42d4-9d7b-e65e37ac0600"
  routeName: "immobile-route-5a5abc33-578c-4499-a4bf-04b6c803f2af"
  command: "any"
  addressBlockIds:
  - "192.168.1.0-192.168.1.100"
  ruleType: "ACCEPT"
