---

# Definir rotas para acesso ao banco de dados ALTERDATA_PACK;
routes:
- routeName: "rota{ALTERDATA_PACK}"
  blockedAddresses: []
  addressFamily: "LOCAL"
  databaseName: "ALTERDATA_PACK"
  remoteAddress: "-"

# Definindo regras para comunicação TCP entre o network-probe e a estação;
rules:
- ruleOrder: 10
  ruleName: "rule{rota{ALTERDATA_PACK}}"
  routeName: "rota{ALTERDATA_PACK}"
  command: "any"
  addressBlockIds:
  - "192.168.1.0-192.168.1.254"
  ruleType: "ACCEPT"
